[build]
  command = "python app.py"  # Replace with your startup command
  functions = "functions/"   # Directory where Netlify Functions are stored
  publish = "static/"        # Optional: Directory to publish (if you have static files)

[context.production.environment]
  PYTHON_VERSION = "3.8"     # Python version used in your environment

[[plugins]]
  package = "@netlify/plugin-functions-core"

[[plugins]]
  package = "@netlify/plugin-nextjs"
